version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 17022003
      MYSQL_DATABASE: project_web
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql vào MySQL container
    networks:
      - app-network

  tomcat:
    build: .  # Dockerfile cùng thư mục
    container_name: tomcat_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql

    environment:
      - DB_URL=jdbc:mysql://mysql_container:3306/project_web?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_USER=root
      - DB_PASSWORD=17022003
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
